const $=s=>document.querySelector(s);let profileId=null,selected=[],step=1,initialMovie=null,initialRating=0,ratingMovie=null,ratingScore=0,usefulnessScore=0;const HISTORY_LIMIT=60;
async function api(url,options){const r=await fetch(url,options),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível concluir a operação.');return d}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function showStep(number){step=number;document.querySelectorAll('.step').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===number));document.querySelectorAll('.progress span').forEach((el,index)=>el.classList.toggle('active',index<number));$('#form-message').textContent=''}
function checkedGenres(){return [...document.querySelectorAll('#genres input:checked')].map(x=>x.value)}
function setStars(container,value){container.querySelectorAll('button').forEach(button=>button.classList.toggle('selected',Number(button.dataset.rating)<=value))}
function setupStars(selector,setter){const box=$(selector);box.querySelectorAll('button').forEach(button=>button.onclick=()=>{setter(Number(button.dataset.rating));setStars(box,Number(button.dataset.rating))})}
function card(item,recommendation=false){const detail=recommendation?`${item.genre_match?'combina com seus gêneros · ':''}${item.method==='collaborative'?`${item.support} vizinhos avaliaram`:'média da comunidade'}`:`Sua nota: ${item.rating}/5`;return `<article class="card"><span class="score">${recommendation?'★ '+item.score.toFixed(2):item.rating+'/5'}</span><h3>${item.title}</h3><p class="meta">${item.genres.join(' · ')||'Sem gênero'}<br>${detail}</p></article>`}
function renderSelected(){const box=$('#selected-films');box.innerHTML=selected.map((film,index)=>`<span>${film.title} · ${'★'.repeat(film.rating)} <button type="button" data-index="${index}" aria-label="Remover ${film.title}">×</button></span>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected.splice(Number(b.dataset.index),1);renderSelected()})}
async function searchMovies(term,box,onPick){if(!term.trim()){box.innerHTML='';return}const movies=await api('/api/movies?q='+encodeURIComponent(term));if(!movies.length){box.innerHTML='<p class="not-found">Filme inexistente</p>';return}box.innerHTML=movies.map(movie=>`<button type="button" data-id="${movie.id}" data-title="${movie.title}"><strong>${movie.title}</strong><small>${movie.genres.join(' · ')}</small></button>`).join('');box.querySelectorAll('button').forEach(button=>button.onclick=()=>{onPick({movie:button.dataset.id,title:button.dataset.title});box.innerHTML=''})}
async function loadProfile(){const [profile,recs]=await Promise.all([api('/api/profile?id='+profileId),api('/api/recommendations?profile='+profileId)]);localStorage.setItem('cinematch-profile-id',String(profileId));$('#profile-name').textContent=`Filmes para ${profile.name}`;$('#recommendations').innerHTML=recs.recommendations.map(item=>card(item,true)).join('');$('#method').textContent='Ordenado por '+recs.method;const total=profile.history.length,shown=profile.history.slice(0,HISTORY_LIMIT);$('#profile-note').textContent=`${total} filme(s) avaliado(s) ${profile.source==='movielens'?'por este usuário na base MovieLens':'por você'}${total>HISTORY_LIMIT?` · mostrando os ${HISTORY_LIMIT} de maior nota`:''}.`;$('#history').innerHTML=shown.map(item=>card(item)).join('');resetUsefulness();$('#profiles-panel').hidden=true;$('#onboarding').hidden=true;$('#dashboard').hidden=false;$('#main-nav').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function showProfiles(){const profiles=await api('/api/profiles');$('#profile-list').innerHTML=profiles.length?'':'<p class="muted">Nenhum perfil criado ainda.</p>';$('#profile-list').innerHTML+=profiles.map(profile=>`<button class="profile-choice ${profile.id===profileId?'current':''}" data-id="${profile.id}"><strong>${profile.name}</strong><span>#${profile.id} · ${profile.genres.join(' · ')}</span></button>`).join('');$('#profile-list').querySelectorAll('button').forEach(button=>button.onclick=async()=>{profileId=Number(button.dataset.id);await loadProfile()});$('#profiles-panel').hidden=false;$('#profiles-panel').scrollIntoView({behavior:'smooth',block:'center'})}
function startNewProfile(){profileId=null;selected=[];initialMovie=null;initialRating=0;$('#profile-form').reset();renderSelected();setStars($('#initial-stars'),0);showStep(1);$('#dashboard').hidden=true;$('#main-nav').hidden=true;$('#onboarding').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
async function restoreSession(){const saved=Number(localStorage.getItem('cinematch-profile-id'));if(!saved)return;try{profileId=saved;await loadProfile()}catch(error){profileId=null;localStorage.removeItem('cinematch-profile-id')}}
function refreshSummary(){api('/api/summary').then(x=>$('#summary').textContent=`${x.ratings.toLocaleString('pt-BR')} avaliações · ${x.movies.toLocaleString('pt-BR')} filmes · ${x.users.toLocaleString('pt-BR')} usuários`)}
function resetUsefulness(){usefulnessScore=0;setStars($('#usefulness-stars'),0);document.querySelectorAll('input[name=watch]').forEach(x=>x.checked=false);$('#usefulness-comment').value='';$('#usefulness-message').textContent=''}
api('/api/genres').then(genres=>$('#genres').innerHTML=genres.filter(g=>g!=='Desconhecido').map(g=>`<label class="chip"><input type="checkbox" value="${g}">${g}</label>`).join(''));refreshSummary();
document.querySelectorAll('.next').forEach(button=>button.onclick=()=>{if(step===1&&!$('#name').value.trim()){$('#name').reportValidity();return}if(step===2&&!checkedGenres().length){$('#form-message').textContent='Escolha ao menos um gênero para continuar.';return}showStep(step+1)});document.querySelectorAll('.back').forEach(button=>button.onclick=()=>showStep(step-1));
setupStars('#initial-stars',value=>initialRating=value);setupStars('#stars',value=>ratingScore=value);setupStars('#usefulness-stars',value=>usefulnessScore=value);
$('#initial-search').oninput=e=>searchMovies(e.target.value,$('#initial-suggestions'),movie=>{initialMovie=movie;$('#initial-search').value=movie.title;$('#initial-picked').textContent=`Filme escolhido: ${movie.title}`});
$('#search').oninput=e=>searchMovies(e.target.value,$('#suggestions'),movie=>{ratingMovie=movie;$('#search').value=movie.title;$('#picked').textContent=`Filme escolhido: ${movie.title}`});
$('#add-film').onclick=()=>{if(!initialMovie||!initialRating){$('#form-message').textContent='Escolha um filme e marque sua nota em estrelas.';return}const row={...initialMovie,rating:initialRating},old=selected.findIndex(x=>x.movie===row.movie);if(old>=0)selected[old]=row;else selected.push(row);initialMovie=null;initialRating=0;$('#initial-search').value='';$('#initial-picked').textContent='Busque e escolha outro filme acima.';setStars($('#initial-stars'),0);renderSelected()};
$('#profile-form').onsubmit=async event=>{event.preventDefault();try{const created=await post('/api/profiles',{name:$('#name').value,genres:checkedGenres(),ratings:selected});profileId=created.id;await loadProfile();refreshSummary()}catch(error){$('#form-message').textContent=error.message}};
document.querySelectorAll('.tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab===button));document.querySelectorAll('.tab-panel').forEach(panel=>panel.classList.toggle('active',panel.id===button.dataset.tab+'-tab'))});
$('#show-profiles').onclick=showProfiles;$('#close-profiles').onclick=()=>$('#profiles-panel').hidden=true;$('#create-profile').onclick=startNewProfile;document.querySelectorAll('#main-nav button').forEach(button=>button.onclick=()=>{if(button.dataset.nav==='profiles')showProfiles();if(button.dataset.nav==='new')startNewProfile();if(button.dataset.nav==='recommendations'){$('#profiles-panel').hidden=true;window.scrollTo({top:0,behavior:'smooth'})}});
$('#save-rating').onclick=async()=>{if(!ratingMovie||!ratingScore){$('#rating-message').textContent='Escolha um filme e marque sua nota em estrelas.';return}try{await post('/api/rating',{profile:profileId,movie:ratingMovie.movie,rating:ratingScore});$('#rating-message').textContent='Avaliação salva. Recomendações atualizadas.';ratingMovie=null;ratingScore=0;$('#search').value='';$('#picked').textContent='Busque e escolha outro filme acima.';setStars($('#stars'),0);await loadProfile();refreshSummary()}catch(error){$('#rating-message').textContent=error.message}};
document.querySelectorAll('.open-ml').forEach(button=>button.onclick=async()=>{const message=button.parentElement.nextElementSibling,id=Number($(button.dataset.input).value);if(!Number.isInteger(id)||id<1||id>943){message.textContent='Informe um número de 1 a 943.';return}message.textContent='';profileId=id;try{await loadProfile()}catch(error){message.textContent=error.message}});
$('#send-usefulness').onclick=async()=>{const watch=document.querySelector('input[name=watch]:checked');if(!usefulnessScore||!watch){$('#usefulness-message').textContent='Marque a nota de utilidade e responda se assistiria.';return}try{await post('/api/feedback',{profile:profileId,usefulness:usefulnessScore,would_watch:watch.value==='1',comment:$('#usefulness-comment').value});resetUsefulness();$('#usefulness-message').textContent='Obrigado! Sua avaliação foi registrada.'}catch(error){$('#usefulness-message').textContent=error.message}};
restoreSession();
